server:
  port: 9010
  servlet:
    context-path: /posts

spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/PostService
    username: postgres
    password: Lakshit@22
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#Eureka Client Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka